Comments/urls.py
from django.urls import path
from . import views
app_name = 'Comments'

urlpatterns = [
    path("", views.index, name="index"),
    path("add/",views.add, name="add"),
    path("update/<int:pk>",views.update, name="update"),
    path("delete/<int:pk>",views.delete, name="delete"),
]

MyStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Comments.urls")),
]

Comments/models.py
from django.db import models
from Elements.models import Element
# Create your models here.

class Comment(models.Model):

    text = models.TextField()
    date_posted = models.DateTimeField(auto_now=False, auto_now_add=True)
    element = models.ForeignKey(Element, related_name="comentario", on_delete=models.CASCADE, null = True)

    class Meta:
        verbose_name = ("Comment")
        verbose_name_plural = ("Comments")

    def __str__(self):
        return f'comentario: {self.id}'

Elements/models.py
from django.db import models
from  django.core.exceptions import ValidationError
# Create your models here
class Category(models.Model):

    title = models.CharField(max_length = 255)
    slug = models.CharField( max_length=50)
    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categorys")

    def __str__(self):
        return self.title

class Type(models.Model):

    title = models.CharField(max_length = 255)
    slug = models.CharField( max_length=50)
    class Meta:
        verbose_name = ("Type")
        verbose_name_plural = ("Types")

    def __str__(self):
        return self.title

class Element(models.Model):

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length = 255, blank = True)
    description = models.TextField()
    price = models.DecimalField( max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category, verbose_name = ("Categorias"), on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    type = models.ForeignKey(Type, verbose_name=("Tipos"), on_delete=models.CASCADE)
    
    #TODO: validacion ejemplo
    
    def clear(self):
        if self.price < 0:
            raise ValidationError('el precio debe se mayor a 0')
    class Meta:
        verbose_name = ("Element")
        verbose_name_plural = ("Elements")

    def __str__(self):
        return self.title

Comments/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment

class CommentForm(ModelForm):
    
    class Meta:
        model = Comment
        fields = ("text",)

Comments/views.py
from django.shortcuts import render, redirect, get_object_or_404,get_list_or_404
from django.core.paginator import Paginator
from .forms import CommentForm
from .models import Comment
# Create your views here.

def index(request):
    all_commment = Comment.objects.all()
    #all_commment = get_list_or_404(Comment, pk__gt=10)
    paginatior = Paginator(all_commment, 2)
    page_nuber = request.GET.get('page')
    comment_page = paginatior.get_page(page_nuber)
        
    context = {
                'Comments': all_commment,
                'comment_page':comment_page,
                'title':'Listado de Comentarios',
                } 
    return render(request, 'comments/index.html', context)


def add(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Comments:index')
    else:
        form = CommentForm()
        
    return render(request, 'comments/add.html',{'page':'Add',
                                                'form': form})


def update(request, pk):
    commet = get_object_or_404(Comment,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=commet)
        if form.is_valid():
            form.save()
            return redirect('Comments:index')
    else:
        form = CommentForm(instance=commet)
    context = {
        'page':'editando',
        'form':form,
        'comment':commet
    }
    return render(request, 'comments/add.html', context)

def delete(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        comment.delete()
    return redirect('Comments:index')

Elements/views.py
from django.shortcuts import render

# Create your views here.

Comments/templates/comments/add.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Page - {{page}}</h1>
        <form method = "post">
            {% csrf_token %}
            <label for="id_text">Text : </label>
            {{form.text}}
            <input type="submit" value = "Eviar">
        </form>
        <script src="" async defer></script>
    </body>
</html>

Comments/templates/comments/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Index</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>{{title}}</h1>
        
        <nav arial-label="page navegation example">
            <ul>
                {% if comment_page.has_previus %}
                    <li class="item_page">
                        <a href="?page={{comment_page.previus_page_number}}">prev</a>
                    </li>
                {% endif %}
                {% for i in comment_page.paginator.page_range %}
                {% if i == comment_page.number %}
                <li class = "page_item active">
                    <a class = "page-link" href="#">{{i}}</a>
                {% else %}
                <li class="page_item">
                    <a class = "page-link" href="?page={{i}}">{{i}}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if comment_page.has_netx %}
                <li class="page_item">
                    <a class = "page-link" href="?page={{comment_page.next_page_number}}">next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        
        {% for commet in Comments  %}
            <ul>
                <li>{{commet.text}} <p>{{commet.date_posted}}</p></li>
                <a href="{% url "Comments:update" commet.id %}">Editar</a>
                <form action = "{% url "Comments:delete" commet.id %}" method = "post">
                    {% csrf_token %}
                    <button type="submit">Borrar</button>
                </form>
                <hr>
            </ul>
        {% endfor %}

        <script src="" async defer></script>
    </body>
</html>